Feat: Add Lemon Squeezy function templates to Console
appwrite/console pull request #1061
Opened 2024-05-01 10:18 UTC by adityaoberai

## What does this PR do?

Adds Lemon Squeezy function templates to Console

## Test Plan

Visit the Functions marketplace to find the added templates

## Related PRs and Issues

https://github.com/appwrite/templates/pull/277

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-05-01 10:39 UTC, adityaoberai commented
@loks0n I am able to see the function templates

- Templates
![image](https://github.com/appwrite/console/assets/31401437/7cbb4f79-fac9-468f-b57a-e89a7f79cac6)

- Payments with Lemon Squeezy
![image](https://github.com/appwrite/console/assets/31401437/c32d3e42-ef4e-4c84-919c-c1b81c20f074)
![image](https://github.com/appwrite/console/assets/31401437/50577178-5cdd-4b83-8c73-5eecf5d82c8c)

- Subscriptions with Lemon Squeezy
![image](https://github.com/appwrite/console/assets/31401437/cd0364d7-b1f3-4d78-94da-7d9266aad475)
![image](https://github.com/appwrite/console/assets/31401437/c578c262-564f-4312-8ec6-8ce53ed86d1b)

2024-05-02 12:04 UTC, loks0n approved these changes

2024-05-21 14:26 UTC, stnguyen90 requested changes
Looks like there's a conflict now

2024-05-22 11:53 UTC, adityaoberai commented
> Looks like there's a conflict now

Just resolved the conflicts
Waiting for tests

2024-05-23 00:36 UTC, stnguyen90 approved these changes

2024-05-23 00:37 UTC, merged