Use Simpler View for Usage Cards
appwrite/console pull request #1242
Opened 2024-07-28 11:45 UTC by ItzNotABug

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-07-31 14:50 UTC, ArmanNik requested changes
I don't think we need to change the `Row ` component, we have the `rowLink` component for that

2024-08-01 07:00 UTC, ItzNotABug commented
> I don't think we need to change the `Row ` component, we have the `rowLink` component for that

Thankss!! Missed that component. Should be fine now.

2024-11-28 07:57 UTC, ernstmul approved these changes

2024-11-28 08:37 UTC, ArmanNik approved these changes

2024-11-28 08:37 UTC, merged