Implement Renaming Attributes
appwrite/console pull request #1304
Opened 2024-08-20 10:40 UTC by PineappleIOnic

## What does this PR do?

This PR implements the ability to rename attributes using the new `newKey` parameter in all updateAttribute routes.

## Related PRs and Issues
https://github.com/appwrite/appwrite/pull/8544

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-08-21 12:18 UTC, ArmanNik requested changes

2024-08-21 12:18 UTC, ArmanNik commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/edit.svelte
> +            originalKey = selectedAttribute.key;
I don't think we need this

2024-08-21 12:18 UTC, ArmanNik commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/attributes/edit.svelte
> +    let originalKey = '';
We can move this one in the 
```js
    $: if (showEdit) {
        currentAttr ??= { ...selectedAttribute };
        originalKey = currentAttr.key;
        error = null;
    }
```

2024-09-05 03:57 UTC, abnegate commented
Pulled into 1.6.1 branch

2024-09-05 03:57 UTC, closed without merging