fix: 'TypeError: o[0].rules[0] is undefined' when trying to execute function
appwrite/console pull request #1364
Opened 2024-09-23 13:18 UTC by askadityapandey

## What does this PR do?

Fixes an issue where the execution window does not show and the page content disappears when executing a function in the console.
fixes #1360

## Test Plan
1. Go to a function.
2. Press Execute in the console.

## Related PRs and Issues
fixes #1360
### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes.

2024-09-23 20:32 UTC, stnguyen90 commented
@askadityapandey, please make sure you comment on the related issue and ask to work on it so that multiple people don't work on the same issue, leading to wasted work.

2024-09-23 20:33 UTC, askadityapandey commented
> @askadityapandey, please make sure you comment on the related issue and ask to work on it so that multiple people don't work on the same issue, leading to wasted work.

Okay, but it'll already show the linked PR🙏😭

2024-09-25 21:11 UTC, stnguyen90 reviewed
> Okay, but it'll already show the linked PR

I'm unable to assign the issue to you, though.

2024-09-25 21:11 UTC, stnguyen90 commented on src/routes/(console)/project-[project]/functions/function-[function]/deploymentDomains.svelte
> +        <p>No rules available</p>
Let's change this to domains as rules wouldn't make sense for most people.

```suggestion
        <p>No domains available</p>
```

2024-09-26 10:44 UTC, TorstenDittmann requested changes
Thank you for the PR, just a small thing to change :)

2024-09-26 10:44 UTC, TorstenDittmann commented on src/routes/(console)/project-[project]/functions/function-[function]/deploymentDomains.svelte
> +    {#if domain && domain.rules && domain.rules.length > 0}
can we make this a bit cleaner by having a variable in the script? 👀 

something like 
```js
$: length: domain?.rules?.length
```

then we can have more simple conditions 👍🏻

2024-09-27 00:13 UTC, stnguyen90 commented
After discussing internally, we want to go with hiding the section (Domains title and URL) altogether if there is no domain.

Thanks for your efforts, but we're going to close this and handle it ourselves. Next time, please comment on the issue and ask to be assigned before submitting a PR to avoid wasted work.

2024-09-27 00:13 UTC, closed without merging