New onboarding flow
appwrite/console pull request #1517
Opened 2024-11-15 14:33 UTC by ernstmul

## What does this PR do?

Work in progress for new onboarding flow

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
✅

2025-01-21 07:44 UTC, ItzNotABug requested changes

2025-01-21 07:44 UTC, ItzNotABug commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +        }
what's this for?

2025-01-21 07:44 UTC, ItzNotABug commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +                                    })}
lets move this calc logic in the `script` tag.

2025-01-21 07:44 UTC, ItzNotABug commented on src/routes/(console)/onboarding/create-project/loading.svelte
> +    ];
Lets check with design if we can get a few more, we don't know for sure how long the project creation can take, say connectivity or region issues. 2 might feel very repetitive or maybe something else.

2025-01-21 07:44 UTC, ItzNotABug commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +            isLoading = false;
lets throw an error notification. I tried to see this locally, and it just kept on loading and no error was indicated to me. We should also probably redirect from the animation in case of an error, wdyt?

2025-01-21 07:44 UTC, ItzNotABug commented on src/routes/(console)/project-[project]/getstarted/+page.svelte
`/get-started`.

2025-01-21 07:44 UTC, ItzNotABug commented on src/routes/(console)/project-[project]/overview/onboard.svelte
> +            }}>Dismiss this page</Button.Button>
Would `Skip` or something else look better? Haven't seen the design on this one yet so.

2025-01-21 07:44 UTC, ItzNotABug commented on src/routes/(console)/project-[project]/overview/onboard.svelte
> +                                src={$app.themeInUse == 'dark'
```suggestion
                                src={$app.themeInUse === 'dark'
```

2025-01-21 07:44 UTC, ItzNotABug commented on src/routes/(console)/project-[project]/overview/onboard.svelte
> +                                src={$app.themeInUse == 'dark'
```suggestion
                                src={$app.themeInUse === 'dark'
```

2025-01-21 07:44 UTC, ItzNotABug commented on src/lib/helpers/onboarding.ts
What if I use a different browser, incognito mode or a different device?
The onboarding would show each and every time. Lets use the team prefs instead.

2025-01-21 07:44 UTC, ItzNotABug commented on static/images/onboarding/appwrite.svg
I think I saw a logo url set as `https://appwrite.io/images/logos/logo.svg` somewhere, lets use the local svg instead.

2025-01-21 07:57 UTC, ItzNotABug requested changes

2025-01-21 07:57 UTC, ItzNotABug commented on src/lib/components/breadcrumbsConsole.svelte
> +        cursor: default;
This seems to make the buttons that use `trigger` class show arrow on hover instead of the pointer cursor.

2025-01-21 12:04 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
Agree, done!

2025-01-21 12:04 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +    $: projectsBottomSheet = {
Otherwise the bottomsheet values don't update when switching organisation!

2025-01-21 12:04 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +    $: organizationsBottomSheet = !selectedOrg
Yeah also I didn't notice the change when switching org, so the projects wouldn't update properly

2025-01-21 12:12 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +    });
Done!

2025-01-21 12:14 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +            <span class="orgNameProject">{selectedOrg?.name ?? 'Organization'}</span>
Done!

2025-01-21 12:14 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +            <span class="orgNameProject">{selectedOrg?.name ?? 'Organization'}</span>
Done!

2025-01-21 12:15 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +                <span class="orgNameProject">{selectedProject.name}</span>
done!

2025-01-21 12:15 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +                <span class="orgNameProject">{selectedProject.name}</span>
Done!

2025-01-21 12:17 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +            {/each}
If I slice it, before I loop it, there's no way (inside the loop) to know if the list was larger than 4 items right? Could do it with a slice, but for now I'll keep it like this if you don't mind it :)

2025-01-21 12:18 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +        outline: none !important;
haha yes! But this time for a Melt-UI override :)

2025-01-21 12:19 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +        border-radius: 12px;
Yep, --border-radius-m. Good one. Changed!

2025-01-21 12:19 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +        border-radius: 0.125rem;
For 2px it doesn't exist. So keeping this one for now then?

2025-01-21 12:31 UTC, ernstmul commented on src/lib/components/sidebar.svelte
> +        border-radius: 8px;
done!

2025-01-21 12:34 UTC, ernstmul commented on src/lib/layout/shell.svelte
> +    });
done

2025-01-21 12:47 UTC, ItzNotABug commented on src/lib/components/navbar.svelte
> +    }
yaa, the utility class. I am pretty sure we might have this later in the lib itself.

2025-01-21 12:48 UTC, ItzNotABug commented on src/routes/(console)/project-[project]/overview/onboard.svelte
> +            }}>Dismiss this page</Button.Button>
I think I saw this in designs, feel free to ignore and mark as resolved.

2025-01-21 12:59 UTC, ernstmul commented on src/lib/layout/shell.svelte
> +        }
Ah yes, this was designed to be more complex but got simplified! Adjusted!

2025-01-21 13:00 UTC, ernstmul commented on src/routes/(console)/onboarding/+page.svelte
> +        <Heading size="4" tag="h2">Create a new organization!</Heading>
Nicely caught! Also sanity debug to see my localhost hotreload does work 😂

2025-01-21 13:01 UTC, ernstmul commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +        }
When the select opens, the flags get loaded into DOM. So you see them flash because they're fetched from the server. By pre-loading them like this, they are instant and don't cause a layout shift!

2025-01-21 13:16 UTC, ernstmul commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +                                    })}
done!

2025-01-21 13:17 UTC, ernstmul commented on src/routes/(console)/onboarding/create-project/loading.svelte
> +    ];
This is somewhere on Sara's todo list. Let me ping her.

2025-01-21 13:21 UTC, ernstmul commented on src/routes/(console)/project-[project]/getstarted/+page.svelte
Done

2025-01-21 13:24 UTC, ernstmul commented on static/images/onboarding/appwrite.svg
That's not the same logo

2025-01-21 13:24 UTC, ernstmul commented on src/lib/components/breadcrumbsConsole.svelte
> +        cursor: default;
Adjusted

2025-01-22 11:53 UTC, ItzNotABug commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +        }
I see, although we could probably use Shimmer component with fixed dimensions we have in Pink2, if design allows it. if not, lets add a comment on this.

2025-01-22 11:56 UTC, ItzNotABug commented on static/images/onboarding/appwrite.svg
Whats the difference apart from size? 👀

2025-01-22 12:06 UTC, ItzNotABug commented on src/routes/(console)/+layout.ts
> +            Query.limit(100),
not that anyone would have more than 100, but that's an issue for some another day 👍.

2025-01-22 12:08 UTC, ItzNotABug reviewed
checked the addressed changes, seem ok. lmk once we move forward.

2025-01-29 11:29 UTC, ernstmul commented on src/routes/(console)/+layout.ts
> +            Query.limit(100),
Yeah agree

2025-01-29 13:43 UTC, TorstenDittmann approved these changes
awesome work! there are a few regression on things I worked on because of overlaps, but I can fix them afterwards 💪🏻

2025-01-29 13:43 UTC, TorstenDittmann commented on src/lib/components/bottom-sheet/SheetMenuBlock.svelte
> +</style>
does it make sense for this to be park of pink itself?

2025-01-29 13:43 UTC, TorstenDittmann commented on src/lib/components/sidebar.svelte
> +<style lang="scss">
how much of this could be migrated to pink v2?

2025-01-29 13:43 UTC, TorstenDittmann commented on src/lib/layout/shell.svelte
> +    };
this might be a bit overkill, EVERY used variable will trigger it, which leads to some room for improvement :-)

2025-01-29 13:43 UTC, TorstenDittmann commented on src/lib/layout/shell.svelte
> +    };
could we break this block down a bit?

2025-01-29 13:43 UTC, TorstenDittmann commented on src/routes/(console)/+layout.ts
> +    const currentOrgId = params.organization ? params.organization : prefs.organization;
this feel a bit "workaroundy" - in what case do we need all projects of an org from the prefs?

2025-01-29 13:43 UTC, TorstenDittmann commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +        }
you could just `fetch` the url, no need to create dom elements 👍🏻

2025-01-29 13:43 UTC, TorstenDittmann commented on src/routes/(console)/project-[project]/databases/header.svelte
> +        <Typography.Title color="--color-fgcolor-neutral-primary" size="xl"
just a reminder to myself, we could use actual values from the token JSON and import it. wanna try a poc on that at some point. wdyt?

2025-01-29 13:43 UTC, TorstenDittmann commented on src/routes/(console)/project-[project]/overview/onboard.svelte
> +    }
we might wanna create global utility functions for that 👍🏻

2025-01-29 13:43 UTC, TorstenDittmann commented on src/routes/(console)/project-[project]/overview/platforms/components/OnboardingPlatformCard.svelte
just a tip, svelte kit routing will actually look into the `/components` folder for a route. In order to tell svelte that this is not a route you can wrap it with `/(components)`. its also easier to navigate 👍🏻

2025-01-29 13:43 UTC, TorstenDittmann commented on src/routes/(console)/project-[project]/overview/platforms/components/OnboardingPlatformCard.svelte
> +        ">
```suggestion
        style:--icon-color={iconColor || 'inherit'}
        style:--icon-size={iconSize ? `${iconSize}rem` : 'inherit'}>
```

I think this should be possible 🤔

2025-01-29 13:43 UTC, TorstenDittmann commented on src/themes/dark.json
> +    "font-family-brand": "Aeonik Pro",
aeonik pro will not be used for "non-cloud" environments, since its a licensed font 👍🏻

2025-01-29 13:43 UTC, TorstenDittmann commented on src/themes/light.json
> +    "font-family-brand": "Aeonik Pro",
same here 👍🏻

2025-01-29 13:46 UTC, ernstmul commented on src/lib/components/bottom-sheet/SheetMenuBlock.svelte
> +</style>
haha, it was. Arman requested it to be in Console because it was to console specific

2025-01-29 14:01 UTC, ItzNotABug requested changes

2025-01-29 14:31 UTC, ernstmul commented on src/lib/components/sidebar.svelte
> +<style lang="scss">
I've cleaned it out a bit (e.g. switched to the Avatar component which I missed here). There is a lot of custom stuff going on, so not everything has a Pink v2 equivalent.

2025-01-29 14:33 UTC, ernstmul commented on src/lib/layout/shell.svelte
> +    };
If I remember correctly this is done like this, because the organizationList isn't always fully filled on page load in all occasions. So by doing it this way the breadcrumb stays up-to-date with the latest of what is fetched.

2025-01-29 14:34 UTC, ernstmul commented on src/routes/(console)/+layout.ts
> +    const currentOrgId = params.organization ? params.organization : prefs.organization;
When you are on a /project-[projectId] url the organization Id cannot be fetched from the url right? And for the new breadcrumbs we need to have all the organisations and the current one all the time.

2025-01-29 14:38 UTC, ernstmul commented on src/routes/(console)/project-[project]/databases/header.svelte
> +        <Typography.Title color="--color-fgcolor-neutral-primary" size="xl"
Yeah would also work 👍

2025-01-29 15:02 UTC, ernstmul commented on src/routes/(console)/project-[project]/overview/onboard.svelte
> +    }
Yes! Was on my todo list, forgot about it. But just fixed it!

2025-01-29 15:03 UTC, ernstmul commented on src/routes/(console)/project-[project]/overview/platforms/components/OnboardingPlatformCard.svelte
Good to know! This was @ItzNotABug's work btw :)

2025-01-29 15:04 UTC, ernstmul commented on src/routes/(console)/project-[project]/overview/platforms/components/OnboardingPlatformCard.svelte
> +        ">
cc @ItzNotABug

2025-01-29 15:04 UTC, ernstmul commented on src/themes/dark.json
> +    "font-family-brand": "Aeonik Pro",
Ah yes, but we do need the correct font in our console. So we should look into that later on!

2025-01-29 15:04 UTC, ernstmul commented on src/themes/light.json
> +    "font-family-brand": "Aeonik Pro",
Same comment!

2025-01-29 15:07 UTC, ernstmul commented on src/lib/components/breadcrumbs.svelte
> +                    <ActionMenu.Item.Anchor href={`/console/organization-${selectedOrg?.$id}`}
No the page loading we do with the loading indicator is smart enough to do nothing when you are on the same page as you would navigate to :)

2025-01-29 15:07 UTC, ernstmul commented on src/lib/components/navbar.svelte
> +    }
Good catch! Yes, there are new designs for the feedback (and support) modals, but they are for a different task. Agreed with Sara to split those to not make this even bigger.

2025-01-29 15:08 UTC, ernstmul commented on src/lib/components/navbar.svelte
Yeah is by design. And: https://github.com/appwrite/console/pull/1517#discussion_r1934065939

2025-01-29 15:09 UTC, ernstmul commented on src/lib/layout/shell.svelte
> +        width: calc(100vw - 200px);
I might have already fixed this. It isn't happening to me locally anymore. What exact viewport are you using?

2025-01-29 15:24 UTC, TorstenDittmann commented on src/routes/(console)/+layout.ts
> +    const currentOrgId = params.organization ? params.organization : prefs.organization;
> When you are on a /project-[projectId] url the organization Id cannot be fetched from the url right? And for the new breadcrumbs we need to have all the organisations and the current one all the time.

but even prefs is not right then here, in this case we'd need to fetch the projects by the project we fetch 👍🏻 

we probably have to fetch the projects under `/project-[projectId]` anyway by the projects `teamId`, since prefs is logic on the frontend and can be out of sync.

2025-01-29 15:57 UTC, ernstmul commented on src/routes/(console)/project-[project]/overview/onboard.svelte
Fixed!

2025-01-29 15:58 UTC, ernstmul commented on src/routes/(console)/project-[project]/functions/header.svelte
> +            >Functions</Typography.Title>
Yeah might be good, but I think for a future improvement? It was already like this. Wdyt?

2025-01-29 15:58 UTC, ernstmul commented on src/routes/(console)/project-[project]/sites/header.svelte
>      </svelte:fragment>
Replied above

2025-01-29 16:00 UTC, ernstmul commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +                    goto(`${base}/project-${project.$id}`);
Ah no, this is the animation time. It redirects you after 3 seconds. Which is the time the animation needs to fully show :)

2025-01-29 16:01 UTC, ernstmul commented on src/routes/(console)/onboarding/create-project/+page.svelte
> +                                    label="Name"
Correct! Added!

2025-01-29 18:19 UTC, merged

2025-01-30 03:48 UTC, ItzNotABug commented on src/routes/(console)/project-[project]/functions/header.svelte
> +            >Functions</Typography.Title>
Hmm, maybe in a different task/PR but we can definitely avoid code duplicacy. A simple `title` var in `Cover` goes fine.