New layout for support and add subject
appwrite/console pull request #1564
Opened 2024-12-16 05:46 UTC by ItzNotABug

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-12-16 14:42 UTC, ernstmul commented on src/lib/components/support.svelte
> +</style>
Let's change this to lang='scss', and then use the nesting to not have to retype the class name.

2024-12-18 08:50 UTC, ernstmul approved these changes

2024-12-30 23:07 UTC, stnguyen90 requested changes

2024-12-30 23:07 UTC, stnguyen90 commented on src/lib/components/support.svelte
> +                    {#if !isPaid}
instead of looking at the plan for premium support, let's look at the current org's plan and check if `premiumSupport` is true.

2025-01-02 12:47 UTC, ItzNotABug commented on src/lib/components/support.svelte
> +                    {#if !isPaid}
Done.

2025-01-09 23:20 UTC, stnguyen90 requested changes

2025-01-09 23:20 UTC, stnguyen90 commented on src/lib/components/support.svelte
> +            link: 'https://github.com/appwrite',
Maybe it would be better to link [here](https://github.com/appwrite/appwrite/issues/new/choose) so it's less clicks and there's less thinking involved in choosing a repo?

```suggestion
            link: 'https://github.com/appwrite/appwrite/issues/new/choose',
```

2025-01-09 23:20 UTC, stnguyen90 commented on src/lib/helpers/date.ts
> +
Why can't we use `shortGeneric` for `timeZoneName` in `Intl.DateTimeFormatOptions` instead?

2025-01-09 23:20 UTC, stnguyen90 commented on src/lib/components/support.svelte
> -{#if isCloud}
Some things shouldn't be shown on self-hosted, right?

2025-01-10 09:41 UTC, ItzNotABug commented on src/lib/helpers/date.ts
> +
1. doesn't fit

  ![image](https://github.com/user-attachments/assets/4b6f80db-2a09-4bfc-869d-a575b5a3cdd8)

2. using regex replace gives a better tz name like `IST` whereas using `shortGeneric` gives `India Time`

  ![image](https://github.com/user-attachments/assets/e5a5b9f1-0963-42ed-b4c4-02cac3546e1c)

2025-01-10 13:05 UTC, ItzNotABug commented on src/lib/components/support.svelte
> -{#if isCloud}
Done.

2025-01-13 09:04 UTC, ernstmul commented on src/lib/components/support.svelte
> +        background: #fff !important;
Can you check all the !importants. And for the hardcoded color vars. Do we have Pink v2 vars for those? We could implement them straight away, with the hardcoded value as fallback. To future proof this.

2025-01-13 09:04 UTC, ernstmul commented on src/routes/(console)/wizard/support/mobileSupportModal.svelte
> +    }
Same about pink v2 color vars with fallback

2025-01-13 09:16 UTC, ItzNotABug commented on src/lib/components/support.svelte
> +        background: #fff !important;
I think we do have the pink2 vars, let me check.

2025-01-14 00:57 UTC, stnguyen90 approved these changes

2025-01-14 00:57 UTC, stnguyen90 commented on src/lib/helpers/date.ts
> +
so frustrating...it looks like we should be using `short`, but it'll show as `GMT+5:30` rather than `IST` because `IST` is vague and can be Israel Standard Time or Irish Standard Time, etc.

Reference: https://github.com/tc39/proposal-temporal/issues/2257#issuecomment-1152070209

Can you add a comment explaining why we need this workaround?

2025-01-14 08:19 UTC, merged