Check features based on plan details instead of plan name
appwrite/console pull request #1570
Opened 2024-12-16 13:23 UTC by ernstmul

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-12-20 00:04 UTC, stnguyen90 requested changes

2024-12-20 00:04 UTC, stnguyen90 commented on src/routes/(console)/project-[project]/databases/database-[database]/backups/containerHeader.svelte
> +                                You are limited to one policy on your plan.
```suggestion
                                You are limited to {maxPolicies} policy on your plan.
```

2024-12-20 04:46 UTC, ItzNotABug approved these changes

2024-12-22 01:30 UTC, stnguyen90 approved these changes

2024-12-22 01:31 UTC, merged