Use new pink tooltip for copy and download icons
appwrite/console pull request #1580
Opened 2024-12-27 11:16 UTC by ernstmul

## What does this PR do?

Use the new Tooltip component for the copy and download buttons

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
✅

2025-01-01 04:16 UTC, ItzNotABug requested changes

2025-01-01 04:16 UTC, ItzNotABug commented on src/lib/components/trim.svelte
> +        ><span class="text u-trim"><slot /></span><span slot="tooltip"
why another `trim` here?

2025-01-01 04:16 UTC, ItzNotABug commented on src/lib/elements/forms/inputOTP.svelte
> -                        class="tooltip"
Not sure why the `class` was removed, is it related to the tooltip directive here? 🤔

2025-01-01 04:16 UTC, ItzNotABug commented on src/lib/elements/forms/inputTags.svelte
> -                    class="tooltip"
same as above.

2025-01-01 04:16 UTC, ItzNotABug commented on src/lib/layout/navigation.svelte
`Tooltip` changes required on other menu items too.

2025-01-01 04:16 UTC, ItzNotABug commented on src/routes/(console)/organization-[organization]/members/+page.svelte
> -                                class="tooltip"
same as above for class.

2025-01-03 06:19 UTC, ernstmul commented on src/lib/elements/forms/inputOTP.svelte
> -                        class="tooltip"
It was only for styling purposes which isn't needed anymore!

2025-01-03 06:19 UTC, ernstmul commented on src/lib/elements/forms/inputTags.svelte
> -                    class="tooltip"
It was only for styling purposes which isn't needed anymore!

2025-01-03 06:19 UTC, ernstmul commented on src/routes/(console)/organization-[organization]/members/+page.svelte
> -                                class="tooltip"
It was only for styling purposes which isn't needed anymore!

2025-01-03 06:19 UTC, ernstmul commented on src/lib/layout/navigation.svelte
Yep, got fixed!

2025-01-03 06:53 UTC, ItzNotABug requested changes

2025-01-03 06:53 UTC, ItzNotABug commented on src/lib/components/copyInput.svelte
>              {#key appendTo}
do we need `#key` if `appendTo` is not used here?

2025-01-03 06:53 UTC, ItzNotABug commented on src/lib/components/eventModal.svelte
>                  {#key copyParent}
same here for `#key`.

2025-01-03 06:53 UTC, ItzNotABug commented on src/routes/(console)/project-[project]/auth/security/updateMockNumbers.svelte
> +                                    <Tooltip
do we have `placement` implementation in the Tooltip component?

2025-01-03 06:53 UTC, ItzNotABug commented on src/routes/(console)/project-[project]/functions/create-function/wizard/steps/templatePermissions.svelte
> +                            <span
we need the slot tooltip defined here, right? 👀

2025-01-03 06:53 UTC, ItzNotABug commented on src/routes/(public)/hackathon/+page.svelte
why does this still exist? 👀

2025-01-03 08:33 UTC, ernstmul commented on src/lib/components/copyInput.svelte
>              {#key appendTo}
Correct! Changed it, and double checked it still worked.

2025-01-03 08:40 UTC, ernstmul commented on src/lib/components/eventModal.svelte
>                  {#key copyParent}
Removed and verified it still works ok! Added a disabled state here as well (no tooltip when the copy is disabled)

2025-01-03 08:41 UTC, ernstmul commented on src/lib/components/trim.svelte
> +        ><span class="text u-trim"><slot /></span><span slot="tooltip"
Otherwise it wouldn't ellipsis properly

2025-01-03 08:44 UTC, ernstmul commented on src/routes/(console)/project-[project]/functions/create-function/wizard/steps/templatePermissions.svelte
> +                            <span
Well spotted! Yes! Added.

2025-01-03 08:51 UTC, ernstmul commented on src/routes/(public)/hackathon/+page.svelte
It's a slot with a different usecase thats also named "tooltip". It still works :)

2025-01-03 09:15 UTC, ItzNotABug commented on src/routes/(public)/hackathon/+page.svelte
I meant the page, pretty sure the route is a very old hackathon thingy.

2025-01-03 11:50 UTC, ernstmul commented on src/routes/(console)/project-[project]/auth/security/updateMockNumbers.svelte
> +                                    <Tooltip
Yeah, but bottom is the default for the new Tooltip component.

2025-01-08 12:44 UTC, ItzNotABug approved these changes

2025-01-08 12:46 UTC, merged