docs: add steps for project development setup
appwrite/console pull request #325
Opened 2023-02-28 05:22 UTC by saurabhmehta1601

## What does this PR do?

Added steps for setting up project for development on local machine including :
1. Cloning repo 
2. Installing dependencies
3. creating .env file from sample.env  

## Test Plan

No tests applicable for documentation changes . 

## Related PRs and Issues

Closes #324

### Have you read the [Contributing Guidelines on issues]
(https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes . I have read the contributing guidelines .

2023-02-28 15:07 UTC, gewenyu99 requested changes
Small comment

2023-02-28 15:07 UTC, gewenyu99 commented on CONTRIBUTING.md
> +add .env file using .env.example file as a template in project root directory
```suggestion
Add a `.env` file by copying the `.env.example` file as a template in the project's root directory.
```

2023-02-28 16:35 UTC, gewenyu99 approved these changes
LGTM

2023-03-01 12:50 UTC, TorstenDittmann approved these changes

2023-03-01 12:51 UTC, merged