Copy Audit: Update document level permission description + add link to move to
appwrite/console pull request #417
Opened 2023-04-24 19:11 UTC by gewenyu99

## What does this PR do?
- Update document level permission description
- Update 

Related to: https://app.asana.com/0/inbox/1201596992745568/1204427666049049/1204438813878753

## Test Plan

https://user-images.githubusercontent.com/29069505/234093010-3b678722-e2b8-4327-9998-bccf386bab47.mov

2023-08-11 11:51 UTC, TGlide requested changes

2023-08-11 11:51 UTC, TGlide commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/+page.svelte
> +            <b> document Level</b>. If collection level permissions are assigned, permissions
Shouldn't Level be all lowercase?

2023-08-11 11:51 UTC, TGlide commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/+page.svelte
> +                            Collection settings</a> to enable document level permissions.
Shouldn't Collection be lowercase?

2023-08-14 15:11 UTC, gewenyu99 commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/+page.svelte
> +            <b> document Level</b>. If collection level permissions are assigned, permissions
Yes, I missed this.

2024-01-02 13:25 UTC, closed without merging