Clarify Deleting Account
appwrite/console pull request #447
Opened 2023-05-18 15:38 UTC by stnguyen90

## What does this PR do?

Console accounts are not actually deleted so a user won't be able to re-create their account after "deleting" it.

## Test Plan

Manual:

![image](https://github.com/appwrite/console/assets/1477010/7e573eae-3b79-4dfc-9947-0ef19a751d39)

## Related PRs and Issues

* https://github.com/appwrite/appwrite/issues/5490 

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-05-19 11:54 UTC, ArmanNik requested changes
@stnguyen90 let's also clear all the locally stored data (both local and session storage), otherwise the user won't be able to login with another account

I would also suggest adding a checkbox for confirmation the same way we do it for documents with relationships :smile:

2023-05-19 15:02 UTC, stnguyen90 commented
@ArmanNik 

> let's also clear all the locally stored data (both local and session storage), otherwise the user won't be able to login with another account

Yep! I plan on submitting a separate PR for that today.

> I would also suggest adding a checkbox for confirmation the same way we do it for documents with relationships

I want to make sure we can roll this out to cloud...are there styling issues with checkboxes for the version cloud is on?

<img width="748" alt="image" src="https://github.com/appwrite/console/assets/1477010/42c245c2-b6b4-426c-8d3d-f6b75cabf90b">

2023-05-21 10:52 UTC, ArmanNik commented
There are still issues with the checkbox style on Cloud... the solution is to update Cloud to the latest version of Appwrite 🙃

2023-05-21 10:54 UTC, ArmanNik approved these changes

2023-08-01 19:50 UTC, eldadfux commented
Not sure about this feature, let's wait. It might be better to just allow deletion and trust backups for any abusive play.

2023-08-02 17:04 UTC, closed without merging