Filtering
appwrite/console pull request #490
Opened 2023-08-04 21:07 UTC by TGlide

2023-08-08 13:18 UTC, ArmanNik commented on src/routes/console/project-[project]/settings/migrations/(import)/step1.svelte
> +                Signed in as test@test.com <button
Does `test@test.com` need to stay here?

2023-08-08 15:41 UTC, TGlide commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/filters.svelte
> +    }
Didn't find them on pink.appwrite.io 🤔

2023-08-08 15:46 UTC, ArmanNik commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/+page.svelte
> +</style>
Yes :)

2023-08-08 22:41 UTC, christyjacob4 commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/+page.ts
> +                Query.orderDesc('$createdAt'),
```suggestion
                Query.orderDesc(''),
```
we have some ongoing index issues with using the $createdAt attribute in ordering . So we use the default ordering based on the internal IDs

2023-08-08 22:41 UTC, christyjacob4 commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/+page.ts
> +    console.log(parsedQueries);
leftover ?

2023-08-08 22:53 UTC, christyjacob4 requested changes
Please address the comments

2023-08-09 13:40 UTC, christyjacob4 approved these changes

2023-08-09 15:47 UTC, merged