Update user labels based on design review:
appwrite/console pull request #503
Opened 2023-08-15 01:34 UTC by stnguyen90

## What does this PR do?

1. Fix typo in labels placeholder
2. Reorder tags and helper text
3. Reduce margin after labels input

## Test Plan

Manual:

<img width="1289" alt="image" src="https://github.com/appwrite/console/assets/1477010/c51cc26a-7904-4600-a700-7014aca7ad20">

## Related PRs and Issues

* https://github.com/appwrite/console/pull/457

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2023-08-15 23:19 UTC, heyCarla requested changes
Everything looks good, just one small change needed!

2023-08-15 23:19 UTC, heyCarla commented on src/routes/console/project-[project]/auth/user-[user]/updateLabels.svelte
>                          <Pill
We should be using the interactive tag component here to suggest the labels, not buttons.

2023-08-16 00:28 UTC, heyCarla approved these changes
NVM, don't know what I was thinking. I just checked the pill again and you're using the right one. All good here!

2023-08-21 18:49 UTC, ArmanNik approved these changes

2023-08-21 18:52 UTC, merged