feat: appwrite dpa
appwrite/console pull request #693
Opened 2023-12-28 13:53 UTC by ArmanNik

2024-01-03 01:14 UTC, gewenyu99 requested changes

2024-01-03 01:14 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +        CEO or Compliance Manager) and submit it to privacy@appwrite.io.
```suggestion
        After downloading, have the DPA signed by your organization's compliance authority, such as your CEO or Compliance Manager, and submit it to privacy@appwrite.io.
```

2024-01-03 01:14 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +        CEO or Compliance Manager) and submit it to privacy@appwrite.io.
I would go as far as to omit the examples for CEO and compliance manager. I think it's for the organization to decide who this person should/can be.

Can we also make sure the email's a link?

2024-01-03 01:14 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +                <b>DPA document (Data Processing Agreement)</b>
```suggestion
                <b>Data Processing Agreement (DPA) document</b>
```

2024-01-03 01:14 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +                <b>DPA document (Data Processing Agreement)</b>
Grammar.

2024-01-03 01:14 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +                <b>DPA document (Data Processing Agreement)</b>
There will be docs under `/docs/advanced/security/dpa`

2024-01-03 01:14 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +                processed.
Let's settle for something simpler and link to docs under `/docs/advanced/security/dpa`

Maybe:

The DPA is a legal document that describes the roles and responsibilities of Appwrite and the organization when personal data is processed. Learn more about the DPA.

2024-01-04 19:36 UTC, gewenyu99 requested changes

2024-01-04 19:36 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +        After downloading, have the DPA signed by your organization's compliance authority, such as your CEO or Compliance Manager, and submit it to privacy@appwrite.io.
Should the email be a link?

2024-01-04 19:36 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +              The DPA is a legal document that describes the roles and responsibilities of Appwrite and the organization when personal data is processed. Learn more about the DPA.
```suggestion
              The DPA is a legal document that describes the roles and responsibilities of Appwrite and the organization when personal data is processed. Learn more about the DPA.
```

The learn more about DPA should be a link 👀

2024-01-04 19:36 UTC, gewenyu99 commented on src/routes/console/organization-[organization]/settings/downloadDPA.svelte
> +              The DPA is a legal document that describes the roles and responsibilities of Appwrite and the organization when personal data is processed. Learn more about the DPA.
I'll provide a link when the docs are finalized.

2024-01-09 13:48 UTC, TorstenDittmann approved these changes

2024-01-09 13:49 UTC, merged