[Feat]: Zoho OAuth Provider Icon
appwrite/console pull request #701
Opened 2023-12-31 11:07 UTC by UtkarshAhuja2003

## What does this PR do?

Adds Zoho Icon for OAuth

## Related PRs and Issues

[#7364](https://github.com/appwrite/appwrite/issues/7364)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

2024-02-22 19:51 UTC, stnguyen90 commented on static/icons/dark/color/zoho.svg
Where'd you find this icon? I couldn't find it on their [branding](https://www.zoho.com/branding/) page. 🧐

2024-02-22 20:35 UTC, UtkarshAhuja2003 commented on static/icons/dark/color/zoho.svg
Got this from [Zoho One](https://www.zoho.com/en-in/one/). I was not able to find a 100x100 Zoho logo😅

2024-02-23 00:38 UTC, stnguyen90 commented on static/icons/dark/color/zoho.svg
Hmm I'm worried that's a specific product...How about their favicon instead? https://www.zohowebstatic.com/sites/zweb/images/favicon.ico

2024-02-23 13:23 UTC, UtkarshAhuja2003 commented on static/icons/dark/color/zoho.svg
Done!

2024-02-24 00:08 UTC, stnguyen90 commented
Dark:
![image](https://github.com/appwrite/console/assets/1477010/6af02419-7b7e-4cdc-85ea-84843ee8264d)

Light:
![image](https://github.com/appwrite/console/assets/1477010/7f451b10-b618-4646-880c-378d3c551924)

2024-02-29 22:19 UTC, stnguyen90 requested changes

2024-02-29 22:19 UTC, stnguyen90 commented on static/icons/dark/color/zoho.svg
Sorry, would you please use these?
[zoho_dark_color.zip](https://github.com/appwrite/console/files/14454114/zoho_dark_color.zip)
[zoho_dark_grayscale.zip](https://github.com/appwrite/console/files/14454115/zoho_dark_grayscale.zip)
[zoho_light_grayscale.zip](https://github.com/appwrite/console/files/14454116/zoho_light_grayscale.zip)
[zoho_light_color.zip](https://github.com/appwrite/console/files/14454117/zoho_light_color.zip)

2024-03-01 07:44 UTC, UtkarshAhuja2003 commented on static/icons/dark/color/zoho.svg
Updated!! Thanks for the icons 😅

![image](https://github.com/appwrite/console/assets/70762626/e1701b46-b815-4233-aac6-59f739475348)


![image](https://github.com/appwrite/console/assets/70762626/c5f775e6-4c11-42ab-992d-2711cc505b14)

2024-03-04 22:54 UTC, stnguyen90 approved these changes

2024-03-11 09:38 UTC, merged