upgrade to SvelteKit 2
appwrite/console pull request #733
Opened 2024-01-17 22:14 UTC by benmccann

## What does this PR do?

Upgrade to SvelteKit 2

## Test Plan

I actually couldn't get this project to build on `main`. This PR fixes it. This is my first PR to the project though, so I wouldn't mind an extra set of eyes

## Related PRs and Issues

I'm also upgrading `prettier` in https://github.com/appwrite/console/pull/725

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

no

2024-01-22 16:16 UTC, TorstenDittmann commented
hey @benmccann 👋🏻 

I'll be able to take some time to review it tomorrow 😄

2024-01-22 16:20 UTC, ArmanNik requested changes
Hey @benmccann thank you for this PR :tada: 
Looks good! I think there are still some `goto` that lead to external sources like 
https://github.com/appwrite/console/blob/e300174f6b810c236d78ab4b57929dfbd1ec88ef/src/routes/auth/magic-url/%2Bpage.svelte#L21
And a couple other places where we redirect to `appwrite-callback-` :+1:

2024-01-22 16:40 UTC, benmccann commented
Thanks for the reviews! I've updated those `goto` calls. I didn't invoke `resolve` in those calls as was being done previously since it's now invoking the browser API directly and there's not really a way for it to succeed or fail that we would worry about and you're no longer in the application once `window.location` has been updated

2024-01-25 15:24 UTC, ArmanNik approved these changes

2024-01-30 14:45 UTC, merged