fix: wizards copy
appwrite/console pull request #884
Opened 2024-02-26 12:16 UTC by loks0n

2024-02-26 15:29 UTC, gewenyu99 commented on src/routes/console/(migration-wizard)/step1.svelte
> +        <!-- @vincentge - What about this? -->
Project

2024-02-26 15:30 UTC, gewenyu99 commented on src/routes/console/project-[project]/overview/platforms/wizard/android/step3.svelte
>      <svelte:fragment slot="title">Initialize SDK</svelte:fragment>
Initialize

2024-02-26 15:30 UTC, gewenyu99 commented on src/routes/console/project-[project]/overview/platforms/wizard/apple/step2.svelte
> +    <!-- @vincentge - What about this? -->
Install

2024-02-26 15:30 UTC, gewenyu99 commented on src/routes/console/project-[project]/overview/platforms/wizard/apple/step3.svelte
> +    <!-- @vincentge - What about this? -->
Initialize

2024-02-26 15:31 UTC, gewenyu99 commented on src/routes/console/project-[project]/overview/platforms/wizard/flutter/step2.svelte
> +    <!-- @vincentge - What about this? -->
See above examples

2024-02-26 15:31 UTC, gewenyu99 commented on src/routes/console/project-[project]/overview/platforms/wizard/flutter/step3.svelte
> +    <!-- @vincentge - What about this? -->
Ditto

2024-02-26 15:31 UTC, gewenyu99 commented on src/routes/console/project-[project]/overview/platforms/wizard/step4.svelte
> +    <!-- @vincentge - What about this? -->
All set

2024-02-26 15:31 UTC, gewenyu99 commented on src/routes/console/wizard/cloudOrganizationChangeTier/usageExcess.svelte
> +        <!-- @vincentge - What about this? -->
This is fine.

2024-02-26 15:31 UTC, gewenyu99 commented on src/routes/console/wizard/feedback/step1.svelte
> +    <!-- @vincentge - What about this? -->
This is fine imo

2024-02-26 15:32 UTC, gewenyu99 commented on src/routes/console/wizard/feedback/step2.svelte
> +    <!-- @vincentge - What about this? -->
Thank you

2024-02-26 15:32 UTC, gewenyu99 commented on src/routes/console/wizard/support/step1.svelte
> +    <!-- @vincentge - What about this? -->
This is fine

2024-02-26 15:32 UTC, gewenyu99 approved these changes
Left suggestions

2024-02-27 01:13 UTC, heyCarla requested changes
Just one typo. Otherwise LGTM!

2024-02-27 01:13 UTC, heyCarla commented on src/routes/console/wizard/feedback/step2.svelte
> +    <svelte:fragment slot="title">Thanks you</svelte:fragment>
```suggestion
    <svelte:fragment slot="title">Thank you</svelte:fragment>
```

2024-02-27 10:37 UTC, TorstenDittmann approved these changes

2024-02-27 10:37 UTC, merged