Update copy for document and collection level permissions
appwrite/console pull request #961
Opened 2024-03-13 10:01 UTC by gewenyu99

## What does this PR do?

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)

## Related PRs and Issues

(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

(Write your answer here.)

2024-03-15 16:33 UTC, stnguyen90 requested changes
Please also make sure to run the formatter to fix the lint errors.

2024-03-15 16:33 UTC, stnguyen90 commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/document-[document]/+page.svelte
> +                        you collection's settings and enable document level permissions. Otherwise,
```suggestion
                        your collection's settings and enable document level permissions. Otherwise, 
```

2024-03-15 16:33 UTC, stnguyen90 commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/settings/updateSecurity.svelte
> +            documents <b>if they have been granted collection level
```suggestion
            documents<b> if they have been granted collection level 
```

2024-03-15 16:33 UTC, stnguyen90 commented on src/routes/console/project-[project]/databases/database-[database]/collection-[collection]/wizard/step2.svelte
> +                you collection's settings and enable document level permissions. Otherwise,
```suggestion
                your collection's settings and enable document level permissions. Otherwise, 
```

2024-03-15 16:33 UTC, stnguyen90 commented on src/routes/console/project-[project]/storage/bucket-[bucket]/create-file/step2.svelte
> +            you bucket's settings and enable file level permissions. Otherwise,
```suggestion
            your bucket's settings and enable file level permissions. Otherwise, 
```

2024-03-15 16:33 UTC, stnguyen90 commented on src/routes/console/project-[project]/storage/bucket-[bucket]/file-[file]/+page.svelte
> +                            you bucket's settings and enable file level permissions. Otherwise,
```suggestion
                            your bucket's settings and enable file level permissions. Otherwise, 
```

2024-03-15 16:33 UTC, stnguyen90 commented on src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte
> +                        files <b>if they have been granted file level
```suggestion
                        files <b>if they have been granted bucket level 
```

2024-03-15 16:33 UTC, stnguyen90 commented on src/routes/console/project-[project]/storage/bucket-[bucket]/create.svelte
> +                you bucket's settings and enable file level permissions. Otherwise,
```suggestion
                your bucket's settings and enable file level permissions. Otherwise, 
```

2024-03-15 16:33 UTC, stnguyen90 commented on src/routes/console/project-[project]/storage/bucket-[bucket]/settings/+page.svelte
> +                            label="File  level permissions" />
```suggestion
                            label="File level permissions" />
```

2024-03-15 16:35 UTC, stnguyen90 requested changes

2024-03-15 16:35 UTC, stnguyen90 commented on src/routes/console/project-[project]/storage/bucket-[bucket]/file-[file]/+page.svelte
>                                  </b>
```suggestion
                                <b>either file or bucket level permissions.</b>
```

2026-09-21 12:09 UTC, eldadfux commented
Starting today this repo is archived. Please raise any issues with the new Appwrite console on the main platform repo: https://github.com/appwrite/appwrite

2026-09-21 12:09 UTC, closed without merging