Tooltip location wrong
appwrite/console pull request #981
Opened 2024-03-19 08:43 UTC by elad2412

- Add fix that element will not get full-line and fill fit is content

2024-04-25 21:51 UTC, stnguyen90 requested changes
Please run `npm run fromat` to fix the lint issue.

2024-04-30 21:54 UTC, stnguyen90 requested changes
Your branch is 160 commits behind main and there are some bugs with it. Please update your branch and run the formatter (`npm run format`) to fix the lint issues.

2024-04-30 22:36 UTC, stnguyen90 commented
Some tooltips are not working. The only one that worked in the following table was the "long" attribute (1000 chars). Even another one with 109 chars didn't show.

<img width="1295" alt="image" src="https://github.com/appwrite/console/assets/1477010/a521f928-8b2c-4e35-9b83-c6eea90be4c8">

2026-09-21 12:09 UTC, eldadfux commented
Starting today this repo is archived. Please raise any issues with the new Appwrite console on the main platform repo: https://github.com/appwrite/appwrite

2026-09-21 12:09 UTC, closed without merging