feat: trial changes
appwrite/console pull request #990
Opened 2024-03-21 16:57 UTC by ArmanNik

2024-04-04 00:24 UTC, stnguyen90 approved these changes

2024-04-04 00:24 UTC, stnguyen90 commented on src/lib/system.ts
> +export const TRIAL_PERIOD_OVERRIDE = true;
This is an override to disable trials? It's a little confusing..I thought it should have been false to disable trials 🧐 . Would it be clearer to name it `DISABLE_TRIAL_PERIOD`?

2024-04-04 19:19 UTC, stnguyen90 commented on src/lib/system.ts
> +export const TRIAL_PERIOD_OVERRIDE = true;
If anything, maybe add a comment? Anyways, you're free to merge whenever.

2024-04-09 21:27 UTC, stnguyen90 requested changes

2024-04-09 21:27 UTC, stnguyen90 commented on src/routes/console/wizard/cloudOrganization/confirmDetails.svelte
> +                    : ` after your trial period ends on ${toLocaleDate(billingPayDate.toString())}`}.
There seems to be an extra period:

<img width="1169" alt="image" src="https://github.com/appwrite/console/assets/1477010/5698bff0-24d9-43bb-971c-d7e983790bdb">

2024-04-18 01:07 UTC, lohanidamodar approved these changes
Looks good.

2024-04-25 03:03 UTC, merged